### ISSUE TITLE
is the "optional extra homework" same as "optional extra psalms" same as "optional extra verses"

### ISSUE THREAD

**Issue by joshuamaxwell** [joshuamaxwell/alongtheway#1]
can we name them all "option extra homework" or something? no big deal if you want them different though

**Comment by fraider** [comment]
I think we could go either way. Usually it's extra verses to look up. Occasionally it's something extra to think about. When all the optional extra verses are Psalms I called it "optional extra Psalms" we could for sure merge "extra verses" with "extra Psalms" (call them the same thing) but I don't know if that will work for "extra homework"?

**Comment by joshuamaxwell** [comment]
ok, sounds good
